# Generated by Django 5.1.3 on 2024-11-11 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consulta',
            options={'ordering': ['dia_da_consulta', 'hora']},
        ),
        migrations.RenameField(
            model_name='consulta',
            old_name='horario',
            new_name='hora',
        ),
        migrations.AddField(
            model_name='consulta',
            name='status',
            field=models.CharField(choices=[('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('pendente', 'Pendente')], default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='medico',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Médico'}, on_delete=django.db.models.deletion.CASCADE, related_name='consultas_medico', related_query_name='consulta_medico', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='paciente',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Paciente'}, on_delete=django.db.models.deletion.CASCADE, related_name='consultas_paciente', related_query_name='consulta_paciente', to=settings.AUTH_USER_MODEL),
        ),
    ]
