# Generated by Django 5.1.3 on 2024-11-12 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_consulta_options_rename_horario_consulta_hora_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='consulta',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='consulta',
            unique_together={('medico', 'dia_da_consulta', 'hora')},
        ),
        migrations.AddField(
            model_name='consulta',
            name='encaminhamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas_encaminhadas', to='home.consulta'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='procedimento',
            field=models.CharField(choices=[('avaliação', 'Avaliação'), ('ortodontia', 'Ortodontia'), ('clareamento', 'Clareamento'), ('próteses', 'Próteses'), ('implantes', 'Implantes')], default='avaliação', max_length=20),
        ),
        migrations.AddField(
            model_name='consulta',
            name='realizada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas_medico', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas_paciente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='status',
        ),
    ]
