# Generated by Django 5.1.3 on 2024-11-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_perfil_especialidade_remove_perfil_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
